# fly.toml app configuration file generated for quotes-frontend on 2025-04-07T16:15:52+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'quotes-frontend'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
