# fly.toml app configuration file generated for quotes-api-thrumming-log-8356 on 2025-04-07T15:13:43+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'quotes-api-thrumming-log-8356'
primary_region = 'ord'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[[mounts]]
  source = 'quotes_data'
  destination = '/app/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
